services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynet

  prefect-orion:
    build:
      context: ./infrastructure/prefect/orion
      dockerfile: Dockerfile
    container_name: prefect-orion
    ports:
      - "4200:4200"
    networks:
      - mynet

  etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl
    environment:
      APP_ROLE: etl
      PREFECT_API_URL: "http://prefect-orion:4200/api"
    depends_on:
      - db
      - prefect-orion
      - redis
    networks:
      - mynet

  metrics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metrics
    environment:
      APP_ROLE: metrics
    depends_on:
      - db
      - redis
    ports:
      - "8082:8082"
    networks:
      - mynet

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynet

volumes:
  pgdata:

networks:
  mynet:
    name: mynet
