apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway:latest 
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  labels:
    app: pushgateway
  annotations:
     prometheus.io/scrape: 'true'
     prometheus.io/port: '9091'
spec:
  selector:
    app: pushgateway
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091