# yaml-language-server: $schema=https://raw.githubusercontent.com/PrefectHQ/prefect/main/src/prefect/server/schemas/core/deployment.json
prefect-version: 3.3.2

name: pipedrive-etl

deployments:
# --- Main ETL Flow (Default Config) ---
- name: Pipedrive Sync
  version: '2.0'
  tags:
  - pipedrive
  - sync
  - etl
  - main
  description: Sincroniza deals recentes do Pipedrive com o banco de dados, usando
    lookups no DB.
  entrypoint: flows/pipedrive_metabase_etl.py:main_etl_flow
  parameters: {}
  work_pool:
    name: docker-pool
    work_queue_name: default
    job_variables:
      image: "mrschrodingers/pipedrive_metabase_integration:latest"
      image_registry: "{{ prefect.blocks.docker-registry-credentials.docker-registry }}"
      image_pull_policy: "Always"
      env:
        PREFECT_API_URL: "http://prefect-orion:4200/api"
        PUSHGATEWAY_ADDRESS: "pushgateway:9091"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      network_mode: "prefect_internal_network"
      mem_limit: "1Gi"
      auto_remove: true
  concurrency_limit: 1
  schedules:
  - interval: 1800.0
    anchor_date: '2025-04-10T12:00:00+00:00'
    timezone: America/Sao_Paulo
    active: true
  pull:
  - prefect.deployments.steps.git_clone:
      repository: https://github.com/MrSchrodingers/pipedrive_metabase_integration.git
      branch: main
      access_token: '{{ prefect.blocks.secret.github-access-token }}'

# --- Backfill Flow (Default Config) ---
- name: Pipedrive Backfill Stage History
  version: '1.0'
  tags:
  - pipedrive
  - backfill
  - history
  description: Preenche o histórico de stages para deals antigos.
  entrypoint: flows/pipedrive_metabase_etl.py:backfill_stage_history_flow
  parameters:
    daily_deal_limit: 10000
    db_batch_size: 1000
  work_pool:
    name: docker-pool
    work_queue_name: default
    job_variables:
      image: "mrschrodingers/pipedrive_metabase_integration:latest"
      image_registry: "{{ prefect.blocks.docker-registry-credentials.docker-registry }}"
      image_pull_policy: "Always"
      env:
        PREFECT_API_URL: "http://prefect-orion:4200/api"
        PUSHGATEWAY_ADDRESS: "pushgateway:9091"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      network_mode: "prefect_internal_network"
      mem_limit: "1Gi"
      auto_remove: true
  schedules: []
  pull:
  - prefect.deployments.steps.git_clone:
      repository: https://github.com/MrSchrodingers/pipedrive_metabase_integration.git
      branch: main
      access_token: '{{ prefect.blocks.secret.github-access-token }}'
  concurrency_limit: 1

# --- Batch Size Experiment (Experiment Config) ---
- name: Batch Size Experiment
  version: '1.0'
  tags:
  - experiment
  - batch-size
  - optimization
  description: Testa diferentes tamanhos de batch, calcula e salva o ótimo na config.
  entrypoint: flows/pipedrive_metabase_etl.py:batch_size_experiment_flow
  parameters:
    batch_sizes:
    - 300
    - 500
    - 750
    - 1000
    - 1500
    test_data_size: 10000
  work_pool:
    name: docker-pool
    work_queue_name: default
    job_variables: 
      image: "mrschrodingers/pipedrive_metabase_integration:latest"
      image_registry: "{{ prefect.blocks.docker-registry-credentials.docker-registry }}"
      image_pull_policy: "Always"
      env:
        PREFECT_API_URL: "http://prefect-orion:4200/api"
        PUSHGATEWAY_ADDRESS: "pushgateway:9091"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      network_mode: "prefect_internal_network"
      mem_limit: "2Gi" 
      auto_remove: true
  schedules: []
  pull:
  - prefect.deployments.steps.git_clone:
      repository: https://github.com/MrSchrodingers/pipedrive_metabase_integration.git
      branch: main
      access_token: '{{ prefect.blocks.secret.github-access-token }}'
  concurrency_limit: 1

# --- Sync Users (Light Config) ---
- name: Sync Pipedrive Users
  version: '1.0'
  tags:
  - pipedrive
  - sync
  - aux
  - users
  description: Sincroniza a tabela pipedrive_users com a API.
  entrypoint: flows/pipedrive_sync_aux.py:sync_pipedrive_users_flow
  parameters: {}
  work_pool:
    name: docker-pool
    work_queue_name: default
    job_variables:
      image: "mrschrodingers/pipedrive_metabase_integration:latest"
      image_registry: "{{ prefect.blocks.docker-registry-credentials.docker-registry }}"
      image_pull_policy: "Always"
      env:
        PREFECT_API_URL: "http://prefect-orion:4200/api"
        PUSHGATEWAY_ADDRESS: "pushgateway:9091"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      network_mode: "prefect_internal_network"
      mem_limit: "512Mi" 
      auto_remove: true
  schedules:
  - cron: 0 3 * * *
    timezone: America/Sao_Paulo
    day_or: true
    active: true
  pull:
  - prefect.deployments.steps.git_clone:
      repository: https://github.com/MrSchrodingers/pipedrive_metabase_integration.git
      branch: main
      access_token: '{{ prefect.blocks.secret.github-access-token }}'
  concurrency_limit: 1

# --- Sync Persons/Orgs (Default Config) ---
- name: Sync Pipedrive Persons and Orgs
  version: '1.0'
  tags:
  - pipedrive
  - sync
  - aux
  - persons
  - orgs
  description: Sincroniza as tabelas pipedrive_persons e pipedrive_organizations.
  entrypoint: flows/pipedrive_sync_aux.py:sync_pipedrive_persons_orgs_flow
  parameters: {}
  work_pool:
    name: docker-pool
    work_queue_name: default
    job_variables: 
      image: "mrschrodingers/pipedrive_metabase_integration:latest"
      image_registry: "{{ prefect.blocks.docker-registry-credentials.docker-registry }}"
      image_pull_policy: "Always"
      env:
        PREFECT_API_URL: "http://prefect-orion:4200/api"
        PUSHGATEWAY_ADDRESS: "pushgateway:9091"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      network_mode: "prefect_internal_network"
      mem_limit: "1Gi"
      auto_remove: true
  schedules:
  - interval: 14400.0
    anchor_date: '2025-04-10T12:00:00+00:00'
    timezone: America/Sao_Paulo
    active: true
  pull:
  - prefect.deployments.steps.git_clone:
      repository: https://github.com/MrSchrodingers/pipedrive_metabase_integration.git
      branch: main
      access_token: '{{ prefect.blocks.secret.github-access-token }}'
  concurrency_limit: 1

# --- Sync Stages/Pipelines (Light Config) ---
- name: Sync Pipedrive Stages and Pipelines
  version: '1.0'
  tags:
  - pipedrive
  - sync
  - aux
  - stages
  - pipelines
  description: Sincroniza as tabelas pipedrive_stages e pipedrive_pipelines.
  entrypoint: flows/pipedrive_sync_aux.py:sync_pipedrive_stages_pipelines_flow
  parameters: {}
  work_pool:
    name: docker-pool
    work_queue_name: default
    job_variables:
      image: "mrschrodingers/pipedrive_metabase_integration:latest"
      image_registry: "{{ prefect.blocks.docker-registry-credentials.docker-registry }}"
      image_pull_policy: "Always"
      env:
        PREFECT_API_URL: "http://prefect-orion:4200/api"
        PUSHGATEWAY_ADDRESS: "pushgateway:9091"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      network_mode: "prefect_internal_network"
      mem_limit: "512Mi" 
      auto_remove: true
  schedules:
  - cron: 0 4 * * *
    timezone: America/Sao_Paulo
    day_or: true
    active: true
  pull:
  - prefect.deployments.steps.git_clone:
      repository: https://github.com/MrSchrodingers/pipedrive_metabase_integration.git
      branch: main
      access_token: '{{ prefect.blocks.secret.github-access-token }}'
  concurrency_limit: 1